### ISSUE TITLE
Refer to the start of the IT student division instead of years since start.

### ISSUE THREAD

**Issue by Tejpbit** [cthit/dokument#27]
The year will need to be updated each time a new honorary member of the student division is elected.
https://github.com/cthit/dokument/blob/master/mallar/hedersmedlemsmall/hedersmedlemsmall.tex#L48

Just update line to:
"En hedersmedlem är en PERSON som synnerligen främjat teknologsektionens intressen och strävanden. Hos Teknologsektionen Informationsteknik har endast ANTAL tidigare personer utnämnts till hedersmedlem **sedan sektionens uppstart 2001.**"

What do you think?
Also, what year was the student division created? Is 2001 correct?

**Comment by ericlp** [comment]
This feels like a neat quality of life update

**Comment by ericlp** [comment]
If wikipedia is a source then 2001 seems to be the correct year.
[Teknologsektionen Informationsteknik](https://sv.wikipedia.org/wiki/Teknologsektionen_Informationsteknik)

**Comment by Sponken** [comment]
Fixed with #50
