### ISSUE TITLE
Move flashit_stadga to /reglemente/sektionskomitteer/

### ISSUE THREAD

**Issue by lindskogen** [cthit/dokument#4]
Why is it in a separate folder?

**Comment by raksooo** [comment]
The directory /reglemente/sektionskomitteer/ contains each committee's part in the "reglemente". Since flashIT isn't a committee it has its own "stadga" which isn't part of the "reglemente" :P Maybe there should be a directory /intresseforeningar/ where documents like this should be.

**Comment by Dr-Horv** [comment]
Yes, @raksooo's suggestion is probably a good way to do it.

**Comment by Ndushi** [comment]
Cool! That is a more correct solution :smile:

**Comment by lindskogen** [comment]
@raksooo is this solved?

**Comment by Sponken** [comment]
FlashIT was made a committee to solve this issues
