### ISSUE TITLE
Add dep and compiler instructions

### ISSUE THREAD

**Issue by bark** [cthit/dokument#7]
In the readme the dependencies for compiling the pdf shood exist. And also how to compile it for someone that don't know LaTeX.

**Comment by ericlp** [comment]
Yee, this would be nice. Different documents fail to compile for different reasons and the error message aren't always very helpful. :upside_down_face:

**Comment by Oscariremma** [comment]
The current readme has instructions nowadays and production builds are handled using GitHub
